name: "Form-AutoGrow"

exports: "form-autogrow.js"

web: "[cpojer.net](http://cpojer.net)"
demo: http://cpojer.net/MooTools/form-autogrow/Demos/

description: "Automatically resizes textareas based on their content."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Christoph Pojer](http://cpojer.net/)"

author: "cpojer"
authors: "[Christoph Pojer](http://cpojer.net)"
category: Forms
tags: [autogrow, textarea]

sources:
    - "Source/Form.AutoGrow.js"
